// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    SidebarLinks: typeof import('./components/SidebarLinks.vue')['default']
    SidebarLogo: typeof import('./components/SidebarLogo.vue')['default']
    SidebarOption: typeof import('./components/SidebarOption.vue')['default']
    SmAccordion: typeof import('@alegradev/smile-ui')['SmAccordion']
    SmAccordionBody: typeof import('@alegradev/smile-ui')['SmAccordionBody']
    SmAccordionHeader: typeof import('@alegradev/smile-ui')['SmAccordionHeader']
    SmAccordionItem: typeof import('@alegradev/smile-ui')['SmAccordionItem']
    SmaSidebarToggler: typeof import('@alegradev/smile-ui-alegra')['SmaSidebarToggler']
    SmIcon: typeof import('@alegradev/smile-ui')['SmIcon']
  }
}

export { }
